# Generated by Django 5.2.5 on 2025-09-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service_servicebooking_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='is_Active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='catergory',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='service',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
